# Generated by Django 2.0 on 2019-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_jornada_competicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='nom_eq1',
            field=models.CharField(default='Nombre equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='jornada',
            name='nom_eq2',
            field=models.CharField(default='Nombre equipo', max_length=100),
        ),
    ]
